### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by dpetrisko**

### CODE REVIEW

**Comment by taylor-bsg** [comment]
Other BSG divisions have determined that squash plus merge into master leads to unhappiness — can you chat with Dustin?

**Comment by dpetrisko** [comment]
I agree -- I'm not planning to squash this

**Comment by dpetrisko** [comment]
This is just a regular merge from dev->master, it's just been a while so there are tons of commits

**Comment by drichmond** [comment]
Has anyone squash + merged into master in the past? 

Or were merges to dev squashed + merged?

**Comment by dpetrisko** [comment]
What am I missing here? 
Master is at 604 commits, dev is at 820 commits, this PR is 216 commits.

**Comment by drichmond** [comment]
I am pretty confused at this point. Did you merge master into dev yesterday?

**Comment by dpetrisko** [comment]
Ohhh, I see the confusion. There was a merge conflict in the README. I resolved the conflict. This shows up as a merge commit in the history.

**Comment by drichmond** [comment]
I'm still confused. Why did master gain commits relative to dev, such that a conflict arose?

**Comment by dpetrisko** [comment]
Because Michael edited the README directly in master

**Comment by drichmond** [comment]
OK. I see that now.

But there are a lot more commits to master than just those, and they are not replicated in dev. 

I think I’m struggling to understand the flow here, just looking at the network diagram. How do changes go from fe_dev, me_dev, be_dev, and dev into master? How do changes propagate into master? Can people push directly to master? 

The reason we’re asking about this is because large merges can be worrisome. A large number of commits can mean many things: A lot of new features (this is fine, not ideal, but fine), no feature-commit squashing (fine, but verbose, and can be confusing, less desirable), something fundamentally wrong with the git flow (e.g. squash + merge, followed by a merge), or something novel and interesting. 

I think we’re trying to make sense of what is going on here, and make sure we’re not backing ourselves into a trap (force push) that could be avoided.

Does that make sense?

**Comment by taylor-bsg** [comment]
Yeah, I think basically, the challenge we are struggling with, is how could
anyone actually review this pull request and confidently say, yes, this
makes sense. And additionally, how would they know logically what
functionality does this new pull request have over the last one?

I know part of the problem is that there is just a long delay from the last
master that we pushed. But looking at the commit log, I would say that 80%
of the descriptions do not convey  enough about what the change was. And
there seems like a lot of intermediate commits are in the log, that do not
correspond to a milestone of additional features or bug fixes to previous
commits, but more like incremental “on the way” commits. Presumably these
should be squashed before being committed to dev?

So my thought here is that perhaps we can refine the policies and flow a
bit to add more structure to the repo metadata...

[In terms of modifying master, the README is forward facing and will need
to be updated out of band with any feature merges from dev. Similarly, we
may need to do some hot fixes (is that the right term? First I am learning
the term hot takes, and now hot fixes..)]

M

**Comment by dpetrisko** [comment]
To be honest, I only made this PR to demonstrate the CI, I didn't intend it to be reviewed... This is just updating master from the latest dev, absolutely nothing fancy happening.

> I think I’m struggling to understand the flow here, just looking at the network diagram. How do changes go from fe_dev, me_dev, be_dev, and dev into master? How do changes propagate into master? Can people push directly to master?

I outline the overall structure here briefly, but I admit it should be more explicit.
https://docs.google.com/document/d/1GOSp6NVQUzGAAk_ahleAsANaQK2XJ0MUOZFPC9DLbLQ/edit#

Basically, 
1) people should do all of their work in feature branches, squash/rebase those commits into a single/few commits before merging into fe_dev, be_dev, me_dev. This is what is not happening right now.

2) When a set of features has been well tested, they should be PRd into dev.  Again, there is no branch protection right now, so people merge into dev without PR.  CI should protect this branch from not being synthesizable and / or failing the functional tests.

3) Once we run PPA regression, long running benchmarks, etc and decide that dev is solid, then we manually update master to dev.  Because this is a straight transfer, there's little (no) chance of it working in dev and not working in master, so this really only needs to be PRd to root out any git funkiness.

3b) Because no one is using master and we have no PPA regression or long-running benchmarks, master just doesn't get updated very often right now.

> [In terms of modifying master, the README is forward facing and will need
> to be updated out of band with any feature merges from dev. Similarly, we
> may need to do some hot fixes (is that the right term? First I am learning
> the term hot takes, and now hot fixes..)]

Yeah, hotfixes should be PRd directly into where they are needed.  Ideally, one would use git cherry-pick to pull that singular commit back into dev, this avoids the merge commit.

> But there are a lot more commits to master than just those, and they are not replicated in dev.

Where do you see this? I only see 3 README commits on master that are not on dev...

**Comment by drichmond** [comment]
> To be honest, I only made this PR to demonstrate the CI, I didn't intend it to be reviewed... This is just updating master from the latest dev, absolutely nothing fancy happening.

Gotcha. That wasn't clear to me. 

> 
> > I think I’m struggling to understand the flow here, just looking at the network diagram. How do changes go from fe_dev, me_dev, be_dev, and dev into master? How do changes propagate into master? Can people push directly to master?
> 
> I outline the overall structure here briefly, but I admit it should be more explicit.
> https://docs.google.com/document/d/1GOSp6NVQUzGAAk_ahleAsANaQK2XJ0MUOZFPC9DLbLQ/edit#
> 
> Basically,
> 
> 1. people should do all of their work in feature branches, squash/rebase those commits into a single/few commits before merging into fe_dev, be_dev, me_dev. This is what is not happening right now.

This is similar to what I enforce in F1 and I like it. If you can enforce it, it is worth the effort.

> 2. When a set of features has been well tested, they should be PRd from <end_dev> into dev.  Again, there is no branch protection right now, so people merge into dev without PR.  CI should protect this dev from not being synthesizable and / or failing the functional tests.

I believe you can define a single branch rule that targets all dev* branches. But yeah, this sounds great.

> 3. Once we run PPA regression, long running benchmarks, etc and decide that dev is solid, then we manually update master to dev.  Because this is a straight transfer, there's little (no) chance of it working in dev and not working in master, so this really only needs to be PRd to root out any git funkiness.

In theory yes :p

> 
> 3b) Because no one is using master and we have no PPA regression or long-running benchmarks, master just doesn't get updated very often right now.
> 
> > [In terms of modifying master, the README is forward facing and will need
> > to be updated out of band with any feature merges from dev. Similarly, we
> > may need to do some hot fixes (is that the right term? First I am learning
> > the term hot takes, and now hot fixes..)]
> 
> Yeah, hotfixes should be PRd directly into where they are needed. Ideally, one would use git cherry-pick to pull that singular commit back into dev, this avoids the merge commit.
> 
> > But there are a lot more commits to master than just those, and they are not replicated in dev.
> 
> Where do you see this? I only see 3 README commits on master that are not on dev...

You're right that there are only three commits right now. But looking at the last month or so - I see several instances of people doing more than README editing and committing to master. These changes have been merged from master to dev ad-hoc.

For example: eddb432

If you're planning to have hotfixes then I would look into closing dev after each merge, and re-open it from that merge commit. Then long-term rebasing of dev becomes simpler, and people can rebase their own branches on the new dev. (It will still be a linear rebase)

**Comment by dpetrisko** [comment]
> You're right that there are only three commits right now. But looking at the last month or so - I see several instances of people doing more than README editing and committing to master. These changes have been merged from master to dev ad-hoc.

Guilty. 

> If you're planning to have hotfixes then I would look into closing dev after each merge, and re-open it from that merge commit. Then long-term rebasing of dev becomes simpler, and people can rebase their own branches on the new dev. (It will still be a linear rebase)

What's the advantage of this over cherry-picking? We have protection against force-pushing on *dev for safety, so we would have to give that up for this scheme.

**Comment by drichmond** [comment]
> On May 17, 2019, at 10:36 AM, Dan Petrisko <notifications@github.com> wrote:
> 
> You're right that there are only three commits right now. But looking at the last month or so - I see several instances of people doing more than README editing and committing to master. These changes have been merged from master to dev ad-hoc.
> 
> Guilty.
> 
> If you're planning to have hotfixes then I would look into closing dev after each merge, and re-open it from that merge commit. Then long-term rebasing of dev becomes simpler, and people can rebase their own branches on the new dev. (It will still be a linear rebase)
> 
> What's the advantage of this over cherry-picking? We have protection against force-pushing on *dev for safety, so we would have to give that up for this scheme.
> 
> 
Are you cherry picking into dev? I guess I’m trying to understand how you would resolve conflicts without reverse merging (which I think looks weird).

**Comment by dpetrisko** [comment]
Ah no, I’m just embracing reverse merging. Hotfixes should be rare and simple, so the commit message can explain them

**Comment by taylor-bsg** [comment]
Okay awesome Dan -- this has been a very helpful discussion -- sorry it seemed like we were shooting the messenger! =) Seems like action items are:

1. Have a BSG wide-document that describes our git flow.  It seems to be that the three of us are mostly in agreement so we can converge across the group. This should targeted toward somebody who is not a git wizard (i.e. your advisor, or EE students), and boils things down to concrete git commands to type.

2. In the doc and to group members directly, specify our squash/merge strategy, and what an adequately specific commit tag is (i.e. "fix bug" -> "fix bug in cache" -> "fix bug in data cache" -> "fix masks-don't-work-on-fpga issues in data cache"

**Comment by dpetrisko** [comment]
Sounds good!

> In the doc and to group members directly, specify our squash/merge strategy, and what an adequately specific commit tag is (i.e. "fix bug" -> "fix bug in cache" -> "fix bug in data cache" -> "fix masks-don't-work-on-fpga issues in data cache"

One thing we should definitely encourage is embedding the issue fixed into the commit (and creating issues for bugs!)

**Comment by dpetrisko** [comment]
I'm merging this now, but I'll make a note to work on the BSG git flow document

**Pull request merged**
