### PR TITLE
Add BHT overriding BTB functionality

### PR DESCRIPTION
**Pull request by dpetrisko**
- Adding a pipeline reg struct in pc_gen
- Rather than always taking BTB entry, we now check BHT whether to 'override' this decision
- Moving riscv defines into bp_common instead of bp_be, so that other Ends can use it

### CODE REVIEW

**Comment by dpetrisko** [comment]
No major changes.  Performance actually stays fairly similar since a 64 entry BTB is huge, probably something like SPEC would show improvement

**Comment by taylor-bsg** [comment]
Maybe you can run on the specs that we have working and see the benefit?
When adding a performance optimization, part of the verification process is
confirming the anticipated benefit.

M

**Comment by dpetrisko** [comment]
Yep, can do

**Comment by dpetrisko** [comment]
Changes moving to larger changeset

**Pull request closed without merging**
