### PR TITLE
Pparrot blackcanary becriticalpathfixes-fix

### PR DESCRIPTION
**Pull request by dpetrisko**
Minor correctness fix for ISA tests (specifically JALR + BLTU)

### CODE REVIEW

**Comment by black-parrot** [comment]
Just a minor question here — the commit log says “minor change” but there are a zillion lines of code that changed. Is this an artifact of how we are using git?

**Comment by dpetrisko** [comment]
Yes. Since we made a branch in the mainline repo for the critical path fixes rather than directly merging my fork branch, this PR is showing up as the original branch + the new fix.  If you click on the "Minor correctness fix" you can see the new, 2-line change

**Comment by taylor-bsg** [comment]
But couldn't you merge this into the branch that you made on the mainline repo?

**Comment by dpetrisko** [comment]
Yeah, I can do that

**Pull request closed without merging**
